---
title: "MDD data exploration"
author: "Heru Handika"
date: "2024-06-23"
output: html_document
---

```{r}
if (!require(pacman)) {
  install.packages(pacman)
}

p_load_gh("hrbrmstr/ggchicklet")

pacman::p_load(here)
pacman::p_load(ggplot2)
pacman::p_load(readr)
pacman::p_load(dplyr)
pacman::p_load(stringr)
pacman::p_load(openxlsx)

source(here::here("R", "utils.R"))
```

## Load Data

```{r}
mdd_path <- here::here("data", "MDD_v1_13.csv")
mdd <- readr::read_csv(mdd_path)

cites <- readr::read_csv(here::here("data", "CITES_2024-10-03-09_19.csv")) |> 
  janitor::clean_names() |> 
  dplyr::filter(class == "Mammalia") |> 
  dplyr::rename(epithet = species) |> 
  dplyr::rename(species = full_name) |> 
  tidyr::drop_na(epithet) |> 
  dplyr::select(c(species, current_listing)) |> 
  dplyr::rename(citesStatus = current_listing)
  
indonesian_names <- readr::read_delim(here::here("data", "nama_indonesia_maryanto.csv"), delim = ";") |> 
  dplyr::rename(species = nama_species) |> 
  dplyr::rename(mainCommonName_ID = nama_indonesia) |> 
  dplyr::mutate(across(everything(),stringr::str_trim))
```

## Clean MDD data and match column names with Biodiv-INA columns

```{r}
indonesia <- mdd |>
  dplyr::filter(stringr::str_detect(countryDistribution, pattern = "Indonesia")) |> 
  # Remove author initial. The REGEX pattern will match any a single letter UTF-8 char
  # followed by dot (.) and whitespaces.
  dplyr::mutate(authority = stringr::str_remove_all(authoritySpeciesAuthor, pattern = "([\\p{L}]{1}\\.\\s)")) |>
  dplyr::mutate(scientificNameAuthorship = ifelse(authorityParentheses == 1, paste0("(",authority, ", ", authoritySpeciesYear, ")"), paste0(authority, ", ", authoritySpeciesYear) )) |> 
  dplyr::mutate(externalTaxonIdentifiers = paste0("mdd:", id)) |> 
  dplyr::mutate(countryDistribution = stringr::str_replace_all(countryDistribution, pattern = "\\|", ";")) |> 
  dplyr::mutate(otherCommonNames = stringr::str_replace_all(otherCommonNames, pattern = "\\|", ";")) |> 
  dplyr::rename(verbatimTypeLocality = typeLocality) |>
  dplyr::rename(taxonOrder = order) |> 
  dplyr::rename(taxonFamily = family) |>
  dplyr::rename(originalNameAsDescribed = originalNameCombination) |> 
  dplyr::rename(mainCommonName_EN = mainCommonName) |> 
  dplyr::rename(otherCommonName_EN = otherCommonNames) |> 
  dplyr::mutate(taxonClass = "Mammalia") |>
  dplyr::mutate(species = paste0(genus, " ", specificEpithet))
  
colnames(indonesia)
colnames(mdd)
colnames(cites)

count <- indonesia |> 
  dplyr::group_by(taxonOrder) |>
  dplyr::count()

order <- indonesia |>
  dplyr::distinct(taxonOrder) |> 
  dplyr::mutate(phyloGroup = "") |>
  dplyr::mutate(phyloGroupSort = "")  
  
readr::write_csv(order, here::here("results", "mdd_indonesia_order.csv"))
```

## Transfer MDD data to the Biodiv-INA template

```{r}
orderData <- readr::read_csv(here::here("data", "mdd_indonesia_order.csv")) |> 
  dplyr::rename(datasetNames = biodivinaMammals)
biodivina <- readr::read_csv(here::here("data", "template_isian_v0_2_0.csv"))

biodivinaCols <- colnames(biodivina)
mdd_ina <- indonesia |>  
  dplyr::select(any_of(biodivinaCols)) |> 
  dplyr::select(-id)

final_data <- biodivina |> 
  dplyr::mutate(phyloGroupSort = as.numeric(phyloGroupSort)) |> 
  dplyr::left_join(mdd_ina, by = "externalTaxonIdentifiers", suffix = c("", "")) |> 
  dplyr::left_join(orderData, by = "taxonOrder", suffix = c("", "")) |> 
  dplyr::left_join(indonesian_names, by = "species", suffix = c("", "")) |> 
  dplyr::left_join(cites, by = "species", suffix = c("", "")) |> 
  dplyr::mutate(kingdom = "Animalia") |>
  dplyr::mutate(phylum = "Chordata") |>
  dplyr::mutate(taxonRank = "species") |> 
  dplyr::mutate(kkID = 405)

colnames(final_data)

readr::write_csv(final_data, here::here("results", "biodivina_mammals.csv"), na = "")
```

## Export to Excel

```{r}
dataset <- orderData |> 
  dplyr::distinct(datasetNames) |> 
  dplyr::pull(datasetNames)

create_dataset <- function(selectedDataset) {
  res <- final_data |> 
    dplyr::filter(datasetNames == selectedDataset)
  
  res
}

wb <- createWorkbook()

write_xlxs <- function(data, name) {
  openxlsx::addWorksheet(
    wb = wb, 
    sheetName = name,
    )
  data |>
    dplyr::select(-datasetNames) |> 
    openxlsx::writeData(
    wb = wb,
    sheet = name,
    )
}

purrr::map(dataset, create_dataset) |> 
  purrr::map2(dataset, write_xlxs)

output_path <- here::here("results", "mammal_indonesia.xlsx")
saveWorkbook(wb, output_path, overwrite = TRUE)
```

## Clean curator names

```{r}
curators <- readr::read_csv(here::here("data", "pj_KK_Mammalia.csv")) |> 
  janitor::clean_names() |> 
  dplyr::rename(taxonFamily = nama_taksa)


final_curators <- final_data |> 
  dplyr::group_by(taxonOrder, taxonFamily, datasetNames, phyloGroupSort) |> 
  dplyr::count(name = "jumlah_taksa") |> 
  dplyr::right_join(curators, by = "taxonFamily") |> 
  dplyr::select(!c(jumlah, no)) |> 
  dplyr::arrange(phyloGroupSort) |> 
  dplyr::relocate(phyloGroupSort)

dataset_counts <- final_data |> 
  dplyr::group_by(datasetNames) |> 
  dplyr::count(name = "taxon_counts")

readr::write_csv(final_curators, here::here("results", "nama_kurator.csv"), na = "")
readr::write_csv(dataset_counts, here::here("results", "dataset_counts.csv"), na = "")
```


